# Generated by Django 5.2.5 on 2025-12-16 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=500, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=500, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Talaba ismi')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar soni')),
                ('correct_answers', models.IntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('wrong_answers', models.IntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('percentage', models.FloatField(default=0, verbose_name='Natija (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlanganmi')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Session ID')),
            ],
            options={
                'verbose_name': 'Talaba natijasi',
                'verbose_name_plural': 'Talaba natijalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Talaba javobi')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'rimi")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Savol')),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.studentresult', verbose_name='Talaba natijasi')),
            ],
            options={
                'verbose_name': 'Talaba javobi',
                'verbose_name_plural': 'Talaba javoblari',
                'ordering': ['student_result', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('test_id', models.CharField(max_length=50, unique=True, verbose_name='Test ID')),
                ('password', models.CharField(max_length=128, verbose_name='Test paroli')),
                ('timer', models.IntegerField(help_text='Daqiqalarda', verbose_name='Timer')),
                ('word_file', models.FileField(blank=True, null=True, upload_to='test_files/', verbose_name='Word fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_active', models.BooleanField(default=False, verbose_name='Test faolmi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.test', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test', verbose_name='Test'),
        ),
    ]
